### PR TITLE
Fix bugs with global styles, status indicator of bindings and filtering in catalog

### LINKED ISSUE #416: Bugs with global styles, status indicator of bindings and with filtering in service catalog
**Description**

After merging new features (add asyncApi component, improve status indicator and remove global styles), there are problems with styles for some parts of out catalog and instances UIs (mainly the color of links), status indicator sometimes shows `NAN` and filtering in the catalog (mainly on labels) does not work.

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Changes proposed in this pull request:
- Fix bugs with global styles (especially `<a>`  tag) after merged #397 
- Fix bug with status indicator of bindings (sometimes number of bindings is `NAN`) after merged #391 
- Fix bug with filtering in catalog (user cannot filtering by connected-app and basic filters) after merged #391 

**Related issue(s)**
#416

### CODE REVIEW

File: instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/StatusIndicator.component.js [hunk 1]
```diff
@@ -32,11 +38,11 @@ const StatusIndicator = ({ data }) => {
             <Status>{statusesStats.PENDING + statusesStats.UNKNOWN}</Status>
           </StatusWrapper>
         ) : null}
-        {statusesStats && statusesStats.FAILED && (
+        {statusesStats && statusesStats.FAILED ? (
```
Comment (pkosiec) [inline instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/StatusIndicator.component.js]: This does exactly the same thing. Why did you change it?

```
{condition ? <Component/> : null}
```

drake-meme copy

---

```
{condition && <Component/>} 
```

drake-meme
