### PR TITLE
Fix UI tests

### LINKED ISSUE #315: UI tests are sometimes failing due to unknown reason
example plan: https://jenkins.poc.servicefactory.cd.ydev.hybris.com/job/azure/job/master/314/console

Some of the failures and caused by not working Dex (or just test are not able to login into dex from some reason) and some tests are (probably) loosing browser context.

### PR DESCRIPTION
**Pull request by akucharska**
**Description**

Changes proposed in this pull request:

- fixes for UI tests 
-- use micro plan during instance creation 
-- wait for remote environment deletion before proceeding with tests
-- add  `--forceExit --detectOpenHandles` flags to prevent tests from not ending properly and to gather more logs

**Related issue(s)**
Resolves #315

### CODE REVIEW

File: tests/ui-tests/commands/console.js [hunk 1]
```diff
@@ -126,9 +126,20 @@ async function createRemoteEnvironment(page, name) {
   await page.waitForSelector(createEnvModal, { hidden: true });
 }
 
+async function getRemoteEnvironmentsWithRetry(page, initialRemoteEnvironments) {
```
Comment (michal-hudy) [inline tests/ui-tests/commands/console.js]: According to name, this function should return RE with a retry. It shouldn't detect changes and there is no retry. Please change the name of the function.

File: tests/ui-tests/commands/common.js [hunk 2]
```diff
@@ -32,8 +37,27 @@ async function testLogin(isTestEnvironmentReady, page) {
   await page.waitForSelector('.sf-toolbar', { visible: true });
 }
 
+async function retry(page, functionToRetry, retryNumber = 3) {
```
Comment (michal-hudy) [inline tests/ui-tests/commands/common.js]:
```js
async function retry(page, functionToRetry, retryNumber = 3) {
  for (let i = 1; i <= retryNumber; i++) {
    console.log('Retrying... Attempt No. ' + i + ' of ' + retryNumber);
    try {
      const returnValue = await functionToRetry();
      return returnValue;
    } catch (e) {
      if (i === retryNumber) {
        console.log('Retry failed:', e);
        throw e;
      }
      await page.waitFor(2000);
    }
  }
}
```

@pkosiec please take a look as I'm not JS expert...

File: tests/package.json [hunk 3]
```diff
@@ -18,7 +18,7 @@
     "faker": "^4.1.0",
     "jest": "^23.6.0",
     "promise-retry": "^1.1.1",
-    "puppeteer": "~1.8.0",
+    "puppeteer": "~1.10.0",
```
Comment (michal-hudy) [inline tests/package.json]: `package.lock` is not updated?
