### PR TITLE
Adjust tabs rendering in catalog and instances views to fetching errors

### LINKED ISSUE #886: The tab with created instances doesn't show when user create instance by class without docs
**Description**

The tab with created instances doesn't show when user create instance from class without any documentation.

**Expected result**

The tab with created instance is show when user create instance from class without any documentation.

**Actual result**

The tab with created instances doesn't show when user create instance from class without any documentation.

**Steps to reproduce**

- Create instance from class without any documentation (md, apispec etc)
- Go to class in catalog

image

image

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Changes proposed in this pull request:
- Adjust rendering of tabs in catalog and instances views to fetching errors
- fix #886 

**Related issue(s)**
See also #886

### CODE REVIEW

File: catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js [hunk 1]
```diff
@@ -217,13 +235,17 @@ class ServiceClassTabs extends Component {
   }
 
   render() {
+    const { serviceClass } = this.props;
     const { docsData, openApiSpec, asyncapi, odata, fetchError } = this.state;
 
+    console.log(serviceClass);
```
Comment (akucharska) [inline catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js]: Remove

File: instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js [hunk 2]
```diff
@@ -231,34 +251,53 @@ class ServiceInstanceTabs extends Component {
...
+            </TabErrorMessageWrapper>
+          )}
+
+          <ServiceInstanceTabsContentWrapper>
+            <Tabs>
+              {!fetchError.docsData && docsData && docsData.length
+                ? docsFromNewApi
+                : null}
+              {!fetchError.openApiSpec && openApiSpec && openApiSpec.source ? (
+                <Tab title={'Console'}>
```
Comment (akucharska) [inline instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js]: move titles to src/variables.js

File: instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js [hunk 3]
```diff
@@ -231,34 +251,53 @@ class ServiceInstanceTabs extends Component {
...
+                  <ApiConsole
+                    url="http://petstore.swagger.io/v1/swagger.json"
+                    schema={openApiSpec.source}
+                  />
+                </Tab>
+              ) : null}
+              {!fetchError.asyncapi && asyncapi && asyncapi.source ? (
+                <Tab title={'Events'} margin="0" background="inherit">
```
Comment (akucharska) [inline instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js]: move titles to src/variables.js

File: instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js [hunk 4]
```diff
@@ -231,34 +251,53 @@ class ServiceInstanceTabs extends Component {
...
+                  <AsyncApi
+                    schema={asyncapi && asyncapi.source}
+                    theme={asyncApiTheme}
+                    config={asyncApiConfig}
+                  />
+                </Tab>
+              ) : null}
+              {!fetchError.odata && odata && odata.source ? (
+                <Tab title={'OData'} margin="0" background="inherit">
```
Comment (akucharska) [inline instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js]: move titles to src/variables.js
