### PR TITLE
Keep existing API in lambda configuration

### LINKED ISSUE #724: API is overwritten on Update
**Description**

If a Lambda API is created with a not default authentication provider, the IDP Settings are overwritten on every lambda update using lambda-ui

**Expected result**

API Object is not changed, if nobody touched it.

**Actual result**

Settings are overwritten with the default IDP settings.

**Steps to reproduce**

1. Create Lambda with HTTP Trigger and use a not default IDP Settings
2. Do changes to the lambda function
3. Check the API Object configuration. It is changed.

**Troubleshooting**

none

### PR DESCRIPTION
**Pull request by k15r**
**Description**

Changes proposed in this pull request:

- existing API configuration was overwritten by default values
**Related issue(s)**

Fixes #724

### CODE REVIEW

File: lambda/src/app/lambdas/lambda-details/lambda-details.component.ts [hunk 1]
```diff
@@ -1174,6 +1177,9 @@ export class LambdaDetailsComponent implements OnInit, OnDestroy {
     if (api.spec.authentication !== undefined) {
       httpEndPoint.isAuthEnabled =
         api.spec.authentication.length !== 0 ? true : false;
+        if (httpEndPoint.isAuthEnabled) {
+          httpEndPoint.authentication = api.spec.authentication[0]
```
Comment (sayanh) [inline lambda/src/app/lambdas/lambda-details/lambda-details.component.ts]: Incase you have more than 1 AuthenticationRule configuration, this won't work.

Comment (sayanh) [reply lambda/src/app/lambdas/lambda-details/lambda-details.component.ts]: As discussed with @joek, this is all good.
